# -*- coding: utf-8 -*-
"""competitors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FzR-G9L1OQx0pyN3mIPTHmeQQswAiUFH
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_curve

def get_rezaeian_features():
    """Returns the exact list of 39 features identified in the Rezaeian study."""
    return [
        'bbc3', 'cdkn2a', 'wfdc2', 'hes2', 'hsd3b7', 'rps6kb1', 'e2f6', 'srd5a3',
        'mmp25', 'mmp21', 'dnah5', 'sf3b1', 'chek2', 'sik1', 'bmpr2', 'hey1',
        'mmp27', 'stmn2', 'mapk3', 'pdgfa', 'taf4b', 'ctbp1', 'igf1r', 'notch2',
        'arid2', 'arid1a', 'spry2', 'cdkn2c', 'gata3', 'spen', 'ccnd2', 'smad2',
        'map3k5', 'prkg1', 'terc', 'hes6', 'nrarp', 'agtr2', 'pde4dip'
    ]

def map_competitor_features(available_columns, competitor_list):
    """Maps the published gene list to the current dataset's column names."""
    mapped = []
    for col in available_columns:
        base_gene = col.replace('_mut', '').lower()
        if base_gene in competitor_list:
            mapped.append(col)

    # Updated message as requested by reviewers
    print(f"Mapped {len(mapped)} features out of the {len(competitor_list)} features selected by the competitor.")
    return mapped

def export_benchmark_matrices(model, X_test, y_test, threshold=0.5, suffix="", save_file=False):
    probs = model.predict_proba(X_test)[:, 1]
    preds = (probs >= threshold).astype(int)
    cm = confusion_matrix(y_test, preds)

    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot(cmap='Blues')
    plt.title(f"Confusion Matrix (Threshold: {threshold:.3f}) {suffix}")

    if save_file:
        plt.savefig(f"benchmark_cm_{suffix.replace(' ', '_')}.png")

    plt.show()