# -*- coding: utf-8 -*-
"""competitors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BOSApsqnqbv8EqUMVat3ESYVNUHsuHW
"""

"""competitors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IyftGkFWQDxCX73t8jm5jaA9JV87r9q5
"""

"""
Logic for benchmarking against competitive models and published gene signatures.
Paper: Rezaeian et al. (2017)
Link: https://doi.org/10.1101/105403
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    roc_curve,
)
from sklearn.model_selection import GridSearchCV

def get_rezaeian_features():
    """Returns the exact list of 39 genes identified in the Rezaeian study."""
    return [
        'bbc3', 'cdkn2a', 'wfdc2', 'hes2', 'hsd3b7', 'rps6kb1', 'e2f6', 'srd5a3',
        'mmp25', 'mmp21', 'dnah5', 'sf3b1', 'chek2', 'sik1', 'bmpr2', 'hey1',
        'mmp27', 'stmn2', 'mapk3', 'pdgfa', 'taf4b', 'ctbp1', 'igf1r', 'notch2',
        'arid2', 'arid1a', 'spry2', 'cdkn2c', 'gata3', 'spen', 'ccnd2', 'smad2',
        'map3k5', 'prkg1', 'terc', 'hes6', 'nrarp', 'agtr2', 'pde4dip'
    ]

def map_competitor_features(available_columns, competitor_list):
    """Maps the published gene list to available mRNA and Mutation columns."""
    mapped = []
    for col in available_columns:
        base_gene = col.replace('_mut', '').lower()
        if base_gene in competitor_list:
            mapped.append(col)

    print(f"Mapped {len(mapped)} features (mRNA + Mutations) from the {len(competitor_list)} genes in the signature.")
    return mapped

def map_competitor_features(available_columns, competitor_list):
    """
    Maps the gene list to exactly one column per gene.
    Prioritizes mRNA expression over Mutation status to reach an exact count.
    """
    mapped = []
    available_set = set(available_columns)

    for gene in competitor_list:
        gene_upper = gene.upper()
        # Try to find the mRNA column
        if gene_upper in available_set:
            mapped.append(gene_upper)
        # If not found, try the Mutation column
        elif f"{gene_upper}_mut" in available_set:
            mapped.append(f"{gene_upper}_mut")

    print(f"Strict Mapping: Found exactly {len(mapped)} features for the {len(competitor_list)} target genes.")
    return mapped

def export_benchmark_matrices(model, X_test, y_test, threshold=None, suffix="", save_file=False):
    """Produces a confusion matrix using PR-Optimal or fixed threshold."""
    probs = model.predict_proba(X_test)[:, 1]
    ap_score = average_precision_score(y_test, probs)

    if threshold is None:
        precisions, recalls, thresholds = precision_recall_curve(y_test, probs)
        f1_scores = (2 * precisions * recalls) / (precisions + recalls + 1e-10)
        best_idx = np.argmax(f1_scores)
        used_threshold = thresholds[min(best_idx, len(thresholds)-1)]
    else:
        used_threshold = threshold

    print(f"[{suffix}] Threshold: {used_threshold:.3f} | AP: {ap_score:.3f}")

    preds = (probs >= used_threshold).astype(int)
    cm = confusion_matrix(y_test, preds)

    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot(cmap='Blues')
    plt.title(f"Confusion Matrix ({suffix})\\nThreshold: {used_threshold:.3f}")

    if save_file:
        plt.savefig(f"benchmark_cm_{suffix.replace(' ', '_')}.png")
    plt.show()